# Generated by Django 4.1.3 on 2022-12-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('surname', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateField()),
            ],
            options={
                'db_table': 'Customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.categories')),
            ],
            options={
                'db_table': 'Items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('id_item', models.IntegerField()),
                ('date_of_order', models.DateField()),
                ('date_of_departure', models.DateField(blank=True, null=True)),
                ('id_customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.customers')),
            ],
            options={
                'db_table': 'Orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id_order_item', models.AutoField(primary_key=True, serialize=False)),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.items')),
                ('id_order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.orders')),
            ],
            options={
                'db_table': 'OrderItem',
                'managed': True,
            },
        ),
    ]
