# Generated by Django 4.1.4 on 2022-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assembly_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
