# Generated by Django 4.1.3 on 2022-12-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_items_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baskets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.customers')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.items')),
            ],
            options={
                'db_table': 'baskets',
                'managed': True,
            },
        ),
    ]
